### ISSUE TITLE
Compatibility issue with vex2.dialog: `message` option is now clobbered. 

### ISSUE THREAD

**Issue by markstos** [bbatliner/vex-dialog#1]
In the original `vex`, it worked to pass `message`  as an option to `prompt`.

In `vex2` dialog, this no longer works: `message` is always assigned a value based on `label`. 

The old behavior should either be restored to be compatible, or the incompatibility should be documented  as an intentional difference.

In my `vex2-safe-dialog` fork, I intend to restore the backwards-compatible behavior.

**Comment by markstos** [comment]
From further reading of the code, it seems the /intent/ to be compatible is there, but there was a challenge when refactoring in having the default value of /message/ reference the the /label/ property which is not defined until later. 

One way to solve something would be to use the "deferred object" pattern used in `node-config` configuration.

Here, a configuration default is set to a "deferred" function, which is only executed /after/ the default value have a chance to be overridden. At this point, the deferred function is executed with the final configuration object passed in. In this way, the default  value for "message" can reference the "label" option which might not be defined until later. 

The "defer function" use in `node-config` is documented here, and you can browse around the code there to find the implementation. 

https://github.com/lorenwest/node-config/wiki/Configuration-Files#javascript-module---js

I contributed that feature to `node-config`. 

For the moment I'm likely to try some other quick and dirty alternative in my branch to see if I can get something working faster. :)

**Comment by markstos** [comment]
See linked commit for my fix: https://github.com/RideAmigosCorp/vex2-safe-dialog/commit/ab395f90b4c43ae970536355be54a3b9a9d91558

**Comment by markstos** [comment]
Ugh, further testing found my "fix" was not a fix at all. Revising.

**Comment by markstos** [comment]
I ended up fixing my own code by updating all calls to `prompt()` to start using `label` instead of `message`.  I'll leave a better fix to someone else.

**Comment by bbatliner** [comment]
It took me a little bit to figure out what you were saying, but I see my error - it was not my intention to lose backwards compatibility with the `message` option in `prompt`. The referenced commit has my solution to the problem, using an internal "dynamic defaults", while keeping the static defaults in case a user wishes to override those defaults. ([Here's a link](https://github.com/bbatliner/vex2-dialog/commit/ab82e56bfd1d4a58ea0e320e35c72012efa70e1b#diff-8499e635520b95e40e6fc5c0333e74deR124) to the specific part of the diff with my solution)

Does this solution help you?

**Comment by markstos** [comment]
Thanks for taking a look at this. I agree parts can be confusing. I solved my personal case by changing by code, but here's an example case to test for backwards compatibility:

```
vex.dialog.prompt({ message : "my message" });
```

That worked in vex1, but in the original version of vex2, it quit working. I'm happy to test if vex2 or vex-dialog are considered ready to test, but I get the feeling you may have already tested this case.

**Comment by bbatliner** [comment]
That test case you provided works now. Thank you for pointing out the problem in my implementation! Closing the issue now...
