### ISSUE TITLE
Bug: Text before first HTML tag and after last HTML tag does not display

### ISSUE THREAD

**Issue by markstos** [bbatliner/vex-dialog#2]
To reproduce:

```
vex.dialog.alert('a<b>c</b>d');
```

The dialog will only display the 'c' character. Text before the first HTML tag and after the last HTML tag is discarded. 

I'm looking at this now, as my "safe" vex2-safe-dialog fork inherited the bug.

**Comment by markstos** [comment]
I confirmed that this a regression from the original vex.dialog function. It does not share this bug. 

I'm reviewing how the code differs now.

**Comment by markstos** [comment]
I've confirmed the bug is in the stringToDom function.

**Comment by markstos** [comment]
The logic bug appears to be this with line:

```
  if (testEl.childElementCount === 1) {
```

The code assumes that if the child element count is "1" then just the child element can be used. Apparently the child element count is 1 even if there is text before or after the singular child element.

**Comment by markstos** [comment]
Ugh. I may return to trying to make a secure dialog library for the original vex library instead. Basing my work on vex2 has uncovered more detours than I hoped to take.

**Comment by bbatliner** [comment]
Hi @markstos, I've been holding off on responding since I work during the week, but I want to point you to [domify](https://www.npmjs.com/package/domify) to solve the problem you're seeing now. I initially was using domify to allow users to pass in both strings and HTML elements as vex2 options, but in the interest of saving kilobytes wrote that small function that was "good enough" at the time. What do you think about using domify to prevent these bugs, even at the cost of a dependency?

**Comment by markstos** [comment]
@bbatliner Thanks for the response. I don't have a strong opinion about adding another dependency or not, but would like to avoid making another HTTP request to get a relatively small library that I need for just this case. If the domify function works can be bundled or inlined that seems OK with me. 

My reality is our application has already loaded jQuery and /that/ dependency is not likely to dropped soon, so the original `vex` solution that relied on jQuery was fine with me. 

I'm going to check out the API for plugging my safe dialog plugin into the original vex and compare that to the effort of getting it to work with vex2. 

I'm also concerned that I might not have found the last compatibility bug in vex2, after finding both the "message" bug and now this one.

**Comment by markstos** [comment]
I read up on browserify over lunch (I'm usually a backend developer). I'm going to take a shot at the `domify` refactor to keep working towards my end goal of a secure-by-default version of `vex dialog`

**Comment by markstos** [comment]
I pushed the domify fix to my secure fork. It should be easy enough to cherry-pick the patch into this branch as well.

**Comment by bbatliner** [comment]
Yup! I'll cherry-pick your patch back into vex2-dialog. The same problem exists in vex2 right now, as well, so I will patch that as well. Thanks for your help! I'll have much more time this weekend to address your issues and work on vex2.
