### ISSUE TITLE
wish: bundling options

### ISSUE THREAD

**Issue by markstos** [bbatliner/vex-dialog#3]
The original vex offered a bundle of the main vex package with the commonly used "dialog" plugin.  This saves an extra HTTP request to fetch the relatively tiny vex2-dialog library. 

It would be nice to offer such a convenience bundle through either the vex2 or vex2-dialog projects.

This would an easy additional build step of the two projects were maintained in the same repo.

**Comment by bbatliner** [comment]
Just added this to the main vex2 repo! Thanks! https://github.com/bbatliner/vex2/commit/978d611a8025d71dd127fef73cb0cc1ffdf9fa39
