### ISSUE TITLE
IE error when cancelling a prompt. 

### ISSUE THREAD

**Issue by simpadat** [bbatliner/vex-dialog#6]
When you cancel a prompt in IE10 (using build 1.0.6) you get an exception stating "Object.keys: argument is not an Object". 
The code fails gracefully in Chrome (results in unresolved value).

When debugging I noticed that when cancelling, the value parameter for promptCallback is false; so in my project I added a line to check whether value is an object prior to retrieve the value from the input.

```
options.callback = function promptCallback(value) {
   if (typeof value === 'object')
      value = value[Object.keys(value)[0]]
   callback(value)
}
```

Could someone please confirm whether this is in line with how the function should behave?

**Comment by bbatliner** [comment]
Confirmed your bug (Object.keys error).

I agree that cancelling the prompt should pass `false` onto the callback to indicate the user cancelled, so your fix is good. I also added another check to pass the empty string ('') to the callback if no `value` is provided.

Code looks like:
```javascript
options.callback = function promptCallback (value) {
    if (typeof value === 'object') {
      var keys = Object.keys(value)
      value = keys.length ? value[keys[0]] : ''
    }
    callback(value)
  }
```

I will push this in version 1.0.7. Thank you!
